# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97a11edf9bc6cd5b263e68e5ae2586a31e1b21f092bee63a44ac2f1e700f43898fc02a42aad52654cfcf2b4c8baffcd0e13b3252978efddeeb9bf52d3455af57

test:
  secret_key_base: e7e953cd685ef08af8f1cb1be94b83339f3029f7f8226ed5f1efd28351837f927fa12b3fa32df02edb880eaf73a7633e7b61d25c86f17a77b30126ebd05065fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
